/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_session_categories_sessionCategories_assignSession_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'categoryId': z.union([z.literal(null), z.intersection(z.string(), z.unknown())]).readonly(),
  'expectedRevision': z.number().readonly(),
})
const _deepseek_ai_dsh_session_categories_sessionCategories_assignSession_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'revision': z.number().readonly(),
  'categories': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'parentId': z.union([z.literal(null), z.intersection(z.string(), z.unknown())]).readonly(),
  'title': z.string().readonly(),
  'order': z.number().readonly(),
})).readonly(),
  'assignments': z.array(z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'categoryId': z.intersection(z.string(), z.unknown()).readonly(),
})).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.literal("workspace-not-found").readonly(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'revision': z.number().readonly(),
}), z.object({
  'code': z.literal("category-not-found").readonly(),
  'categoryId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("parent-not-found").readonly(),
  'parentId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("cross-workspace").readonly(),
}), z.object({
  'code': z.literal("cycle").readonly(),
}), z.object({
  'code': z.literal("anchor-not-found").readonly(),
  'anchorId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("session-not-in-workspace").readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("archive-failed").readonly(),
  'operationId': z.intersection(z.string(), z.unknown()).readonly(),
})]).readonly(),
})])
const _deepseek_ai_dsh_session_categories_sessionCategories_create_parameter_0$schema = z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'parentId': z.union([z.literal(null), z.intersection(z.string(), z.unknown())]).readonly(),
  'title': z.string().readonly(),
  'beforeCategoryId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'expectedRevision': z.number().readonly(),
})
const _deepseek_ai_dsh_session_categories_sessionCategories_create_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'revision': z.number().readonly(),
  'categories': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'parentId': z.union([z.literal(null), z.intersection(z.string(), z.unknown())]).readonly(),
  'title': z.string().readonly(),
  'order': z.number().readonly(),
})).readonly(),
  'assignments': z.array(z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'categoryId': z.intersection(z.string(), z.unknown()).readonly(),
})).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.literal("workspace-not-found").readonly(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'revision': z.number().readonly(),
}), z.object({
  'code': z.literal("category-not-found").readonly(),
  'categoryId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("parent-not-found").readonly(),
  'parentId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("cross-workspace").readonly(),
}), z.object({
  'code': z.literal("cycle").readonly(),
}), z.object({
  'code': z.literal("anchor-not-found").readonly(),
  'anchorId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("session-not-in-workspace").readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("archive-failed").readonly(),
  'operationId': z.intersection(z.string(), z.unknown()).readonly(),
})]).readonly(),
})])
const _deepseek_ai_dsh_session_categories_sessionCategories_deleteCategory_parameter_0$schema = z.object({
  'categoryId': z.intersection(z.string(), z.unknown()).readonly(),
  'operationId': z.intersection(z.string(), z.unknown()).readonly(),
  'expectedRevision': z.number().readonly(),
})
const _deepseek_ai_dsh_session_categories_sessionCategories_deleteCategory_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'revision': z.number().readonly(),
  'categories': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'parentId': z.union([z.literal(null), z.intersection(z.string(), z.unknown())]).readonly(),
  'title': z.string().readonly(),
  'order': z.number().readonly(),
})).readonly(),
  'assignments': z.array(z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'categoryId': z.intersection(z.string(), z.unknown()).readonly(),
})).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.literal("workspace-not-found").readonly(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'revision': z.number().readonly(),
}), z.object({
  'code': z.literal("category-not-found").readonly(),
  'categoryId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("parent-not-found").readonly(),
  'parentId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("cross-workspace").readonly(),
}), z.object({
  'code': z.literal("cycle").readonly(),
}), z.object({
  'code': z.literal("anchor-not-found").readonly(),
  'anchorId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("session-not-in-workspace").readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("archive-failed").readonly(),
  'operationId': z.intersection(z.string(), z.unknown()).readonly(),
})]).readonly(),
})])
const _deepseek_ai_dsh_session_categories_sessionCategories_get_parameter_0$schema = z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_session_categories_sessionCategories_get_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'revision': z.number().readonly(),
  'categories': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'parentId': z.union([z.literal(null), z.intersection(z.string(), z.unknown())]).readonly(),
  'title': z.string().readonly(),
  'order': z.number().readonly(),
})).readonly(),
  'assignments': z.array(z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'categoryId': z.intersection(z.string(), z.unknown()).readonly(),
})).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.literal("workspace-not-found").readonly(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_session_categories_sessionCategories_moveCategory_parameter_0$schema = z.object({
  'categoryId': z.intersection(z.string(), z.unknown()).readonly(),
  'parentId': z.union([z.literal(null), z.intersection(z.string(), z.unknown())]).readonly(),
  'beforeCategoryId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'expectedRevision': z.number().readonly(),
})
const _deepseek_ai_dsh_session_categories_sessionCategories_moveCategory_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'revision': z.number().readonly(),
  'categories': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'parentId': z.union([z.literal(null), z.intersection(z.string(), z.unknown())]).readonly(),
  'title': z.string().readonly(),
  'order': z.number().readonly(),
})).readonly(),
  'assignments': z.array(z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'categoryId': z.intersection(z.string(), z.unknown()).readonly(),
})).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.literal("workspace-not-found").readonly(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'revision': z.number().readonly(),
}), z.object({
  'code': z.literal("category-not-found").readonly(),
  'categoryId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("parent-not-found").readonly(),
  'parentId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("cross-workspace").readonly(),
}), z.object({
  'code': z.literal("cycle").readonly(),
}), z.object({
  'code': z.literal("anchor-not-found").readonly(),
  'anchorId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("session-not-in-workspace").readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("archive-failed").readonly(),
  'operationId': z.intersection(z.string(), z.unknown()).readonly(),
})]).readonly(),
})])
const _deepseek_ai_dsh_session_categories_sessionCategories_moveSessions_parameter_0$schema = z.object({
  'sessionIds': z.array(z.intersection(z.string(), z.unknown())).readonly(),
  'categoryId': z.union([z.literal(null), z.intersection(z.string(), z.unknown())]).readonly(),
  'expectedRevision': z.number().readonly(),
})
const _deepseek_ai_dsh_session_categories_sessionCategories_moveSessions_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'revision': z.number().readonly(),
  'categories': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'parentId': z.union([z.literal(null), z.intersection(z.string(), z.unknown())]).readonly(),
  'title': z.string().readonly(),
  'order': z.number().readonly(),
})).readonly(),
  'assignments': z.array(z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'categoryId': z.intersection(z.string(), z.unknown()).readonly(),
})).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.literal("workspace-not-found").readonly(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'revision': z.number().readonly(),
}), z.object({
  'code': z.literal("category-not-found").readonly(),
  'categoryId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("parent-not-found").readonly(),
  'parentId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("cross-workspace").readonly(),
}), z.object({
  'code': z.literal("cycle").readonly(),
}), z.object({
  'code': z.literal("anchor-not-found").readonly(),
  'anchorId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("session-not-in-workspace").readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("archive-failed").readonly(),
  'operationId': z.intersection(z.string(), z.unknown()).readonly(),
})]).readonly(),
})])
const _deepseek_ai_dsh_session_categories_sessionCategories_rename_parameter_0$schema = z.object({
  'categoryId': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'expectedRevision': z.number().readonly(),
})
const _deepseek_ai_dsh_session_categories_sessionCategories_rename_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'revision': z.number().readonly(),
  'categories': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'parentId': z.union([z.literal(null), z.intersection(z.string(), z.unknown())]).readonly(),
  'title': z.string().readonly(),
  'order': z.number().readonly(),
})).readonly(),
  'assignments': z.array(z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'categoryId': z.intersection(z.string(), z.unknown()).readonly(),
})).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.literal("workspace-not-found").readonly(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'revision': z.number().readonly(),
}), z.object({
  'code': z.literal("category-not-found").readonly(),
  'categoryId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("parent-not-found").readonly(),
  'parentId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("cross-workspace").readonly(),
}), z.object({
  'code': z.literal("cycle").readonly(),
}), z.object({
  'code': z.literal("anchor-not-found").readonly(),
  'anchorId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("session-not-in-workspace").readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("archive-failed").readonly(),
  'operationId': z.intersection(z.string(), z.unknown()).readonly(),
})]).readonly(),
})])
const _deepseek_ai_dsh_session_categories_sessionCategories_reorderCategory_parameter_0$schema = z.object({
  'categoryId': z.intersection(z.string(), z.unknown()).readonly(),
  'beforeCategoryId': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'expectedRevision': z.number().readonly(),
})
const _deepseek_ai_dsh_session_categories_sessionCategories_reorderCategory_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'revision': z.number().readonly(),
  'categories': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'parentId': z.union([z.literal(null), z.intersection(z.string(), z.unknown())]).readonly(),
  'title': z.string().readonly(),
  'order': z.number().readonly(),
})).readonly(),
  'assignments': z.array(z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'categoryId': z.intersection(z.string(), z.unknown()).readonly(),
})).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.literal("workspace-not-found").readonly(),
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'revision': z.number().readonly(),
}), z.object({
  'code': z.literal("category-not-found").readonly(),
  'categoryId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("parent-not-found").readonly(),
  'parentId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("cross-workspace").readonly(),
}), z.object({
  'code': z.literal("cycle").readonly(),
}), z.object({
  'code': z.literal("anchor-not-found").readonly(),
  'anchorId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("session-not-in-workspace").readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("archive-failed").readonly(),
  'operationId': z.intersection(z.string(), z.unknown()).readonly(),
})]).readonly(),
})])

export const TYPERT = {
  package: '@deepseek-ai/dsh-session-categories',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-session-categories#sessionCategories/assignSession',
      service: 'sessionCategories',
      namespace: 'sessionCategories',
      method: 'assignSession',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session-categories/types#SessionCategoryAssignRequest',
            schema: _deepseek_ai_dsh_session_categories_sessionCategories_assignSession_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-session-categories/types#SessionCategoryMutationResult',
        schema: _deepseek_ai_dsh_session_categories_sessionCategories_assignSession_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/session-categories/src/index.ts","line":182,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-session-categories#sessionCategories/create',
      service: 'sessionCategories',
      namespace: 'sessionCategories',
      method: 'create',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session-categories/types#SessionCategoryCreateRequest',
            schema: _deepseek_ai_dsh_session_categories_sessionCategories_create_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-session-categories/types#SessionCategoryMutationResult',
        schema: _deepseek_ai_dsh_session_categories_sessionCategories_create_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/session-categories/src/index.ts","line":89,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-session-categories#sessionCategories/deleteCategory',
      service: 'sessionCategories',
      namespace: 'sessionCategories',
      method: 'deleteCategory',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session-categories/types#SessionCategoryDeleteRequest',
            schema: _deepseek_ai_dsh_session_categories_sessionCategories_deleteCategory_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-session-categories/types#SessionCategoryMutationResult',
        schema: _deepseek_ai_dsh_session_categories_sessionCategories_deleteCategory_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/session-categories/src/index.ts","line":212,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-session-categories#sessionCategories/get',
      service: 'sessionCategories',
      namespace: 'sessionCategories',
      method: 'get',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session-categories/types#SessionCategoryGetRequest',
            schema: _deepseek_ai_dsh_session_categories_sessionCategories_get_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-session-categories/types#SessionCategoryGetResult',
        schema: _deepseek_ai_dsh_session_categories_sessionCategories_get_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/session-categories/src/index.ts","line":81,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-session-categories#sessionCategories/moveCategory',
      service: 'sessionCategories',
      namespace: 'sessionCategories',
      method: 'moveCategory',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session-categories/types#SessionCategoryMoveRequest',
            schema: _deepseek_ai_dsh_session_categories_sessionCategories_moveCategory_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-session-categories/types#SessionCategoryMutationResult',
        schema: _deepseek_ai_dsh_session_categories_sessionCategories_moveCategory_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/session-categories/src/index.ts","line":124,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-session-categories#sessionCategories/moveSessions',
      service: 'sessionCategories',
      namespace: 'sessionCategories',
      method: 'moveSessions',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session-categories/types#SessionCategoryMoveSessionsRequest',
            schema: _deepseek_ai_dsh_session_categories_sessionCategories_moveSessions_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-session-categories/types#SessionCategoryMutationResult',
        schema: _deepseek_ai_dsh_session_categories_sessionCategories_moveSessions_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/session-categories/src/index.ts","line":188,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-session-categories#sessionCategories/rename',
      service: 'sessionCategories',
      namespace: 'sessionCategories',
      method: 'rename',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session-categories/types#SessionCategoryRenameRequest',
            schema: _deepseek_ai_dsh_session_categories_sessionCategories_rename_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-session-categories/types#SessionCategoryMutationResult',
        schema: _deepseek_ai_dsh_session_categories_sessionCategories_rename_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/session-categories/src/index.ts","line":113,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-session-categories#sessionCategories/reorderCategory',
      service: 'sessionCategories',
      namespace: 'sessionCategories',
      method: 'reorderCategory',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session-categories/types#SessionCategoryReorderRequest',
            schema: _deepseek_ai_dsh_session_categories_sessionCategories_reorderCategory_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-session-categories/types#SessionCategoryMutationResult',
        schema: _deepseek_ai_dsh_session_categories_sessionCategories_reorderCategory_result$schema,
      },
      sourceLocation: {"file":"packages/workspace/session-categories/src/index.ts","line":167,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Durable category service. Mutations are serialized by one settled queue.",
        "summary": "Durable category service.",
        "tags": [],
        "jsDoc": "/** Durable category service. Mutations are serialized by one settled queue. */",
        "key": "sessionCategories",
        "exportName": "SessionCategoriesService",
        "members": [
          {
            "kind": "method",
            "name": "get",
            "signature": "@Remote('get') get(request: SessionCategoryGetRequest): SessionCategoryGetResult",
            "summary": "Read categories and assignments belonging to one Workspace.",
            "jsDoc": "/** Read categories and assignments belonging to one Workspace. */"
          },
          {
            "kind": "method",
            "name": "create",
            "signature": "@Remote('create') create(request: SessionCategoryCreateRequest): Promise<SessionCategoryMutationResult>",
            "summary": "Create one category.",
            "jsDoc": "/** Create one category. */"
          },
          {
            "kind": "method",
            "name": "rename",
            "signature": "@Remote('rename') rename(request: SessionCategoryRenameRequest): Promise<SessionCategoryMutationResult>",
            "summary": "Rename one category.",
            "jsDoc": "/** Rename one category. */"
          },
          {
            "kind": "method",
            "name": "moveCategory",
            "signature": "@Remote('moveCategory') moveCategory(request: SessionCategoryMoveRequest): Promise<SessionCategoryMutationResult>",
            "summary": "Move one category to another parent and/or sibling position.",
            "jsDoc": "/** Move one category to another parent and/or sibling position. */"
          },
          {
            "kind": "method",
            "name": "reorderCategory",
            "signature": "@Remote('reorderCategory') reorderCategory(request: SessionCategoryReorderRequest): Promise<SessionCategoryMutationResult>",
            "summary": "Reorder a category among current siblings.",
            "jsDoc": "/** Reorder a category among current siblings. */"
          },
          {
            "kind": "method",
            "name": "assignSession",
            "signature": "@Remote('assignSession') assignSession(request: SessionCategoryAssignRequest): Promise<SessionCategoryMutationResult>",
            "summary": "Assign or clear one Session.",
            "jsDoc": "/** Assign or clear one Session. */"
          },
          {
            "kind": "method",
            "name": "moveSessions",
            "signature": "@Remote('moveSessions') moveSessions(request: SessionCategoryMoveSessionsRequest): Promise<SessionCategoryMutationResult>",
            "summary": "Assign or clear multiple Sessions.",
            "jsDoc": "/** Assign or clear multiple Sessions. */"
          },
          {
            "kind": "method",
            "name": "deleteCategory",
            "signature": "@Remote('deleteCategory') deleteCategory(request: SessionCategoryDeleteRequest): Promise<SessionCategoryMutationResult>",
            "summary": "Recursively remove a category after archiving its assigned Sessions.",
            "jsDoc": "/** Recursively remove a category after archiving its assigned Sessions. */"
          },
          {
            "kind": "method",
            "name": "snapshotAll",
            "signature": "snapshotAll(): SessionCategoryDocument",
            "summary": "Current full document for invariant companions.",
            "jsDoc": "/** Current full document for invariant companions. */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "PendingCategoryArchive",
            "declaration": "export interface PendingCategoryArchive {\n    readonly operationId: SessionCategoryOperationId;\n    readonly categoryIds: readonly SessionCategoryId[];\n    readonly sessionIds: readonly SessionId[];\n}"
          },
          {
            "name": "SessionCategory",
            "declaration": "export interface SessionCategory {\n    readonly id: SessionCategoryId;\n    readonly workspaceId: WorkspaceId;\n    readonly parentId: SessionCategoryId | null;\n    readonly title: string;\n    readonly order: number;\n}"
          },
          {
            "name": "SessionCategoryAnchorNotFound",
            "declaration": "export interface SessionCategoryAnchorNotFound {\n    readonly code: 'anchor-not-found';\n    readonly anchorId: SessionCategoryId;\n}"
          },
          {
            "name": "SessionCategoryArchiveFailed",
            "declaration": "export interface SessionCategoryArchiveFailed {\n    readonly code: 'archive-failed';\n    readonly operationId: SessionCategoryOperationId;\n}"
          },
          {
            "name": "SessionCategoryAssignment",
            "declaration": "export interface SessionCategoryAssignment {\n    readonly sessionId: SessionId;\n    readonly categoryId: SessionCategoryId;\n}"
          },
          {
            "name": "SessionCategoryAssignRequest",
            "declaration": "export interface SessionCategoryAssignRequest {\n    readonly sessionId: SessionId;\n    readonly categoryId: SessionCategoryId | null;\n    readonly expectedRevision: number;\n}"
          },
          {
            "name": "SessionCategoryCreateRequest",
            "declaration": "export interface SessionCategoryCreateRequest {\n    readonly workspaceId: WorkspaceId;\n    readonly parentId: SessionCategoryId | null;\n    readonly title: string;\n    readonly beforeCategoryId?: SessionCategoryId;\n    readonly expectedRevision: number;\n}"
          },
          {
            "name": "SessionCategoryCrossWorkspace",
            "declaration": "export interface SessionCategoryCrossWorkspace {\n    readonly code: 'cross-workspace';\n}"
          },
          {
            "name": "SessionCategoryCycle",
            "declaration": "export interface SessionCategoryCycle {\n    readonly code: 'cycle';\n}"
          },
          {
            "name": "SessionCategoryDeleteRequest",
            "declaration": "export interface SessionCategoryDeleteRequest {\n    readonly categoryId: SessionCategoryId;\n    readonly operationId: SessionCategoryOperationId;\n    readonly expectedRevision: number;\n}"
          },
          {
            "name": "SessionCategoryDocument",
            "declaration": "export interface SessionCategoryDocument {\n    readonly version: 1;\n    readonly revision: number;\n    readonly categories: readonly SessionCategory[];\n    readonly assignments: readonly SessionCategoryAssignment[];\n    readonly pendingArchive: readonly PendingCategoryArchive[];\n}"
          },
          {
            "name": "SessionCategoryFailure",
            "declaration": "export type SessionCategoryFailure = SessionCategoryRevisionConflict | SessionCategoryWorkspaceNotFound | SessionCategoryNotFound | SessionCategoryParentNotFound | SessionCategoryCrossWorkspace | SessionCategoryCycle | SessionCategoryAnchorNotFound | SessionCategorySessionNotInWorkspace | SessionCategoryArchiveFailed;"
          },
          {
            "name": "SessionCategoryGetRequest",
            "declaration": "export interface SessionCategoryGetRequest {\n    readonly workspaceId: WorkspaceId;\n}"
          },
          {
            "name": "SessionCategoryGetResult",
            "declaration": "export type SessionCategoryGetResult = SessionCategorySuccess | { readonly ok: false; readonly error: SessionCategoryWorkspaceNotFound; };"
          },
          {
            "name": "SessionCategoryId",
            "declaration": "export type SessionCategoryId = Branded<'SessionCategoryId'>;"
          },
          {
            "name": "SessionCategoryMoveRequest",
            "declaration": "export interface SessionCategoryMoveRequest {\n    readonly categoryId: SessionCategoryId;\n    readonly parentId: SessionCategoryId | null;\n    readonly beforeCategoryId?: SessionCategoryId;\n    readonly expectedRevision: number;\n}"
          },
          {
            "name": "SessionCategoryMoveSessionsRequest",
            "declaration": "export interface SessionCategoryMoveSessionsRequest {\n    readonly sessionIds: readonly SessionId[];\n    readonly categoryId: SessionCategoryId | null;\n    readonly expectedRevision: number;\n}"
          },
          {
            "name": "SessionCategoryMutationResult",
            "declaration": "export type SessionCategoryMutationResult = SessionCategorySuccess | SessionCategoryRejected;"
          },
          {
            "name": "SessionCategoryNotFound",
            "declaration": "export interface SessionCategoryNotFound {\n    readonly code: 'category-not-found';\n    readonly categoryId: SessionCategoryId;\n}"
          },
          {
            "name": "SessionCategoryOperationId",
            "declaration": "export type SessionCategoryOperationId = Branded<'SessionCategoryOperationId'>;"
          },
          {
            "name": "SessionCategoryParentNotFound",
            "declaration": "export interface SessionCategoryParentNotFound {\n    readonly code: 'parent-not-found';\n    readonly parentId: SessionCategoryId;\n}"
          },
          {
            "name": "SessionCategoryRejected",
            "declaration": "export interface SessionCategoryRejected {\n    readonly ok: false;\n    readonly error: SessionCategoryFailure;\n}"
          },
          {
            "name": "SessionCategoryRenameRequest",
            "declaration": "export interface SessionCategoryRenameRequest {\n    readonly categoryId: SessionCategoryId;\n    readonly title: string;\n    readonly expectedRevision: number;\n}"
          },
          {
            "name": "SessionCategoryReorderRequest",
            "declaration": "export interface SessionCategoryReorderRequest {\n    readonly categoryId: SessionCategoryId;\n    readonly beforeCategoryId?: SessionCategoryId;\n    readonly expectedRevision: number;\n}"
          },
          {
            "name": "SessionCategoryRevisionConflict",
            "declaration": "export interface SessionCategoryRevisionConflict {\n    readonly code: 'revision-conflict';\n    readonly revision: number;\n}"
          },
          {
            "name": "SessionCategorySessionNotInWorkspace",
            "declaration": "export interface SessionCategorySessionNotInWorkspace {\n    readonly code: 'session-not-in-workspace';\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "SessionCategorySnapshot",
            "declaration": "export interface SessionCategorySnapshot {\n    readonly revision: number;\n    readonly categories: readonly SessionCategory[];\n    readonly assignments: readonly SessionCategoryAssignment[];\n}"
          },
          {
            "name": "SessionCategorySuccess",
            "declaration": "export interface SessionCategorySuccess {\n    readonly ok: true;\n    readonly value: SessionCategorySnapshot;\n}"
          },
          {
            "name": "SessionCategoryWorkspaceNotFound",
            "declaration": "export interface SessionCategoryWorkspaceNotFound {\n    readonly code: 'workspace-not-found';\n    readonly workspaceId: WorkspaceId;\n}"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "WorkspaceId",
            "declaration": "export type WorkspaceId = WorkspaceIdBrand;"
          },
          {
            "name": "WorkspaceId",
            "declaration": "export type WorkspaceId = Branded<'WorkspaceId'>;"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
