/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { SessionCategoryAssignRequest, SessionCategoryCreateRequest, SessionCategoryDeleteRequest, SessionCategoryGetRequest, SessionCategoryGetResult, SessionCategoryMoveRequest, SessionCategoryMoveSessionsRequest, SessionCategoryMutationResult, SessionCategoryRenameRequest, SessionCategoryReorderRequest } from '@deepseek-ai/dsh-session-categories/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$73657373696f6e43617465676f72696573 {
    assignSession: (request: SessionCategoryAssignRequest) => Promise<RemoteResult<SessionCategoryMutationResult>>
    create: (request: SessionCategoryCreateRequest) => Promise<RemoteResult<SessionCategoryMutationResult>>
    deleteCategory: (request: SessionCategoryDeleteRequest) => Promise<RemoteResult<SessionCategoryMutationResult>>
    get: (request: SessionCategoryGetRequest) => Promise<RemoteResult<SessionCategoryGetResult>>
    moveCategory: (request: SessionCategoryMoveRequest) => Promise<RemoteResult<SessionCategoryMutationResult>>
    moveSessions: (request: SessionCategoryMoveSessionsRequest) => Promise<RemoteResult<SessionCategoryMutationResult>>
    rename: (request: SessionCategoryRenameRequest) => Promise<RemoteResult<SessionCategoryMutationResult>>
    reorderCategory: (request: SessionCategoryReorderRequest) => Promise<RemoteResult<SessionCategoryMutationResult>>
  }
  interface TypertRemoteMap {
    'sessionCategories/assignSession': (request: SessionCategoryAssignRequest) => Promise<RemoteResult<SessionCategoryMutationResult>>
    'sessionCategories/create': (request: SessionCategoryCreateRequest) => Promise<RemoteResult<SessionCategoryMutationResult>>
    'sessionCategories/deleteCategory': (request: SessionCategoryDeleteRequest) => Promise<RemoteResult<SessionCategoryMutationResult>>
    'sessionCategories/get': (request: SessionCategoryGetRequest) => Promise<RemoteResult<SessionCategoryGetResult>>
    'sessionCategories/moveCategory': (request: SessionCategoryMoveRequest) => Promise<RemoteResult<SessionCategoryMutationResult>>
    'sessionCategories/moveSessions': (request: SessionCategoryMoveSessionsRequest) => Promise<RemoteResult<SessionCategoryMutationResult>>
    'sessionCategories/rename': (request: SessionCategoryRenameRequest) => Promise<RemoteResult<SessionCategoryMutationResult>>
    'sessionCategories/reorderCategory': (request: SessionCategoryReorderRequest) => Promise<RemoteResult<SessionCategoryMutationResult>>
  }
  interface TypertRemoteNamespaceMap {
    'sessionCategories': TypertRemoteNamespace$73657373696f6e43617465676f72696573
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
